package:
    name: api-history-crawler
    version: "1.0.1"

source:
    git_rev: 1.0.1
    git_url: https://github.com/brittainhard/api_crawler.git

requirements:
    build:
        - python
        - setuptools
    run:
        - python
